// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as MenuScreen from "./MenuScreen.bs.js";
import * as BoardsScreen from "./BoardsScreen.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setPrompt = match[1];
  var prompt = match[0];
  var match$1 = React.useState(function () {
        return {
                message: "",
                level: /* NONE */3
              };
      });
  var setAlert = match$1[1];
  var alert = match$1[0];
  var match$2 = React.useState(function () {
        return /* DEFAULT */0;
      });
  var setCurrentShellTab = match$2[1];
  var match$3 = alert.level;
  var tmp;
  switch (match$3) {
    case /* ERROR */0 :
        tmp = React.createElement("div", {
              className: "error"
            }, alert.message);
        break;
    case /* WARNING */1 :
        tmp = React.createElement("div", {
              className: "warning"
            }, alert.message);
        break;
    case /* INFO */2 :
        tmp = React.createElement("div", {
              className: "info"
            }, alert.message);
        break;
    case /* NONE */3 :
        tmp = React.createElement(React.Fragment, undefined);
        break;
    
  }
  var tmp$1;
  switch (match$2[0]) {
    case /* DEFAULT */0 :
        tmp$1 = React.createElement(React.Fragment, undefined);
        break;
    case /* MENU */1 :
        tmp$1 = React.createElement(MenuScreen.make, {});
        break;
    case /* BOARDS */2 :
        tmp$1 = React.createElement(BoardsScreen.make, {});
        break;
    
  }
  return React.createElement("div", {
              className: "terminal"
            }, React.createElement("header", undefined, React.createElement("div", undefined, React.createElement("span", {
                          className: "close"
                        }), React.createElement("span", {
                          className: "min"
                        }), React.createElement("span", {
                          className: "max"
                        })), React.createElement("h3", {
                      className: "terminal-title"
                    }, "Kanban Shell")), React.createElement("main", undefined, React.createElement("section", {
                      className: "prompt"
                    }, React.createElement("div", {
                          className: "wrapper"
                        }, React.createElement("span", undefined, "IP address @:"), React.createElement("form", {
                              onSubmit: (function (e) {
                                  e.preventDefault();
                                  var match = prompt.toUpperCase();
                                  if (match === "MENU") {
                                    return Curry._1(setCurrentShellTab, (function (param) {
                                                  return /* MENU */1;
                                                }));
                                  } else {
                                    return Curry._1(setAlert, (function (param) {
                                                  return {
                                                          message: "invalid command",
                                                          level: /* ERROR */0
                                                        };
                                                }));
                                  }
                                })
                            }, React.createElement("input", {
                                  className: "input-prompt",
                                  autoFocus: true,
                                  value: prompt,
                                  onChange: (function (e) {
                                      Curry._1(setPrompt, e.target.value);
                                      Curry._1(setCurrentShellTab, (function (param) {
                                              return /* DEFAULT */0;
                                            }));
                                      return Curry._1(setAlert, (function (param) {
                                                    return {
                                                            message: "",
                                                            level: /* NONE */3
                                                          };
                                                  }));
                                    })
                                }))), React.createElement("div", {
                          className: "prompt-feedback"
                        }, tmp)), tmp$1));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
