// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function BoardsScreen(Props) {
  return React.createElement("div", undefined, "boards");
}

var make = BoardsScreen;

export {
  make ,
  
}
/* react Not a pure module */
