// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function BoardColumn(Props) {
  var title = Props.title;
  return React.createElement("div", undefined, title);
}

var make = BoardColumn;

export {
  make ,
  
}
/* react Not a pure module */
