// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BoardColumn from "./BoardColumn.bs.js";

function MenuScreen(Props) {
  return React.createElement("section", {
              className: "menu"
            }, React.createElement("ul", {
                  tabIndex: 0
                }, React.createElement("li", undefined, "home"), React.createElement("li", undefined, "boards"), React.createElement("li", undefined, "help")), React.createElement("article", {
                  className: "shell-screen",
                  id: "home-screen"
                }, React.createElement("svg", {
                      className: "sub-title",
                      viewBox: "0 0 125 60"
                    }, React.createElement("text", {
                          y: "20"
                        }, "Welcome To")), React.createElement("svg", {
                      className: "main-title",
                      viewBox: "0 0 125 40"
                    }, React.createElement("text", {
                          y: "15"
                        }, "Kanban Shell"))), React.createElement("article", {
                  className: "shell-screen",
                  id: "boards-screen"
                }, React.createElement("div", {
                      className: "col-container"
                    }, React.createElement("div", {
                          className: "col ice-box"
                        }, React.createElement(BoardColumn.make, {
                              title: "Ice Box"
                            })), React.createElement("div", {
                          className: "col in-progress"
                        }, React.createElement(BoardColumn.make, {
                              title: "In Progress"
                            })), React.createElement("div", {
                          className: "col done"
                        }, React.createElement(BoardColumn.make, {
                              title: "Done"
                            })))), React.createElement("article", {
                  className: "shell-screen",
                  id: "help-screen"
                }, React.createElement("h3", undefined, "Help")), React.createElement("div", {
                  className: "legend"
                }));
}

var make = MenuScreen;

export {
  make ,
  
}
/* react Not a pure module */
