// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Ticket(Props) {
  var title = Props.title;
  return React.createElement("div", undefined, React.createElement("h3", undefined, title));
}

var make = Ticket;

export {
  make ,
  
}
/* react Not a pure module */
